version: '3.4'

services:
  pythondev:
    image: pythondev
    build:
      context: ../.
      dockerfile: ./dev/Dockerfile
    working_dir: /app
    environment:
      NODE_ENV: development
    # ports:
    #   - 3000:3000
    #   - 9229:9229
    volumes:
      - "..:/app"
      - ~/.gitconfig:/core/.gitconfig
    command: sleep infinity
